"""initial setup

Revision ID: 31bf0f9a984e
Revises: 
Create Date: 2025-07-09 00:54:42.195502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31bf0f9a984e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_nodes', sa.Column('type', sa.String(), nullable=True))
    op.add_column('map_nodes', sa.Column('dependency', sa.String(), nullable=True))
    op.add_column('map_nodes', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('map_nodes', sa.Column('your_note', sa.String(), nullable=True))
    op.alter_column('map_nodes', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_map_nodes_id'), 'map_nodes', ['id'], unique=False)
    op.add_column('question_answers', sa.Column('ques_ans', sa.JSON(), nullable=False))
    op.add_column('question_answers', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('question_answers_map_node_id_fkey'), 'question_answers', type_='foreignkey')
    op.create_foreign_key(None, 'question_answers', 'workspace', ['workspace_id'], ['id'])
    op.drop_column('question_answers', 'map_node_id')
    op.drop_column('question_answers', 'question_data')
    op.add_column('workspace', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('workspace', sa.Column('prior_knowledge', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('root_node_id', sa.Integer(), nullable=True))
    op.alter_column('workspace', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_workspace_id'), 'workspace', ['id'], unique=False)
    op.create_foreign_key(None, 'workspace', 'map_nodes', ['root_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_index(op.f('ix_workspace_id'), table_name='workspace')
    op.alter_column('workspace', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('workspace', 'root_node_id')
    op.drop_column('workspace', 'prior_knowledge')
    op.drop_column('workspace', 'progress')
    op.add_column('question_answers', sa.Column('question_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('question_answers', sa.Column('map_node_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question_answers', type_='foreignkey')
    op.create_foreign_key(op.f('question_answers_map_node_id_fkey'), 'question_answers', 'map_nodes', ['map_node_id'], ['id'])
    op.drop_column('question_answers', 'workspace_id')
    op.drop_column('question_answers', 'ques_ans')
    op.drop_index(op.f('ix_map_nodes_id'), table_name='map_nodes')
    op.alter_column('map_nodes', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('map_nodes', 'your_note')
    op.drop_column('map_nodes', 'is_completed')
    op.drop_column('map_nodes', 'dependency')
    op.drop_column('map_nodes', 'type')
    # ### end Alembic commands ###
